### ISSUE TITLE
Clickable vertical lines

### ISSUE THREAD

**Issue by dgorissen** [drarmstr/c3#18]
I have a zoomable area chart with some (fixed) vertical lines (with labels). I would like to make the labels & lines clickable (ie, the whole thing).  I have managed to make the lines clickable using the events property on line_options. However you really have to aim carefully with the mouse to trigger the event.

The events option has no effect inside label_options it seems. Tried going through the class property but I suspect the zooming may be interfering. Any suggestions?

**Comment by drarmstr** [comment]
It is definitely a usability concern.  For draggable lines C3 added support for this.  If you use the straight line layers you can enable `draggable` behaviour.  This will create a hidden draggable element that is wider then the visible line so it is easier to drag.  The Worldbank example demonstrates this.  The top timeline has straight red dotted lines that are draggable.  You'll notice they are draggable not just over the lines themselves, but from a wider area.  It should be doable to expose a `drag_line_options` that could create these additional elements even if the draggable behaviour is not enabled.

**Comment by drarmstr** [comment]
Ok, now if you define `drag_line_options` you can set events for the hidden line that is wider than the actual visible line for user interactions.

**Comment by dgorissen** [comment]
Excellent, thanks! FYI, in my use case the vertical lines represent different types of events that happen over time (= x axis). Clicking them gives more information elsewhere in the page.

Ideally I also wanted to give them their own glyph, attached to the top of the line. Don't believe there is a direct API for that but figured I could add a scatter plot layer to simulate that.
