### ISSUE TITLE
Area chart with negative values

### ISSUE THREAD

**Issue by dgorissen** [drarmstr/c3#19]
Is there a way to have the area char deal with negative values. E.g., say I have a line graph that dips under the x-axis. I would want to ensure its the area between the x-axis and the line that gets colored for both the positive and negative values.

Here is a d3 illustration of the concept I found.  Not the prettiest but illustrates the general idea: http://jsfiddle.net/C5gYv/

Is there an easy way to get c3 do do something like this?

**Comment by drarmstr** [comment]
I haven't personally played with negative values for area charts.  That would obviously present a challenge if you were stacking.  But, for the single stack case, it should be doable.  What problems occur if you make an area chart with negative values?  You can set the `baseline` property to `0` in the `Plot.Layer.Area` to facilitate this when setting a vertical domain with a negative bottom.

**Comment by dgorissen** [comment]
setting `baseline: 0` does the trick, thanks!

**Comment by dgorissen** [comment]
Just as an FYI for those that google. I needed to show the value of the area plot at the point under the cursor. This method worked great in the events property of the Area options field: https://bl.ocks.org/mbostock/3902569

**Comment by Sachin4dotnet** [comment]
I have updated that fiddle and achieve this - 
[http://jsfiddle.net/sachin4dotnet/C5gYv/31/](http://jsfiddle.net/sachin4dotnet/C5gYv/31/)
