### ISSUE TITLE
Library name conflict

### ISSUE THREAD

**Issue by tmld** [drarmstr/c3#2]
Hi Douglas,

I'd recommend changing the name of your project. There is already a project called C3.js:
http://c3js.org/

I liked the tables from your examples, and tried to install your library using "bower install c3", which appeared to work, however I ended up installing the 'other' C3.

It's a tad confusing.

**Comment by drarmstr** [comment]
Yes, I recently became aware of this conflict.  There was a long process to get naming and open source approval in my organization and by the time this got posted another project had started using a different name, but with the same abbreviation.  I may look at a name change to avoid confusion, but it will require another name approval process.

**Comment by drarmstr** [comment]
What do you think about "Versatile Visualization Vault"?

**Comment by drarmstr** [comment]
Unfortunately "V3" is also already taken.  For now it is published in NPM as "q3" pending possible renaming.

**Comment by drarmstr** [comment]
To avoid this conflict a new repository [drarmstr/chartcollection](https://github.com/drarmstr/chartcollection) has been created with the name `chartcollection`.  It has been published on NPM using `chartcollection` as well.
